create table if not exists public.indicator_download_events (
  id bigint generated by default as identity primary key,
  product_code text not null,
  platform text not null check (platform in ('CTRADER', 'MT4', 'MT5')),
  downloaded_at timestamptz not null default now()
);

create index if not exists idx_indicator_download_events_product_time
  on public.indicator_download_events (product_code, downloaded_at desc);

alter table public.indicator_download_events enable row level security;

drop policy if exists "service_role_indicator_download_events" on public.indicator_download_events;
create policy "service_role_indicator_download_events"
  on public.indicator_download_events
  for all
  to service_role
  using (true)
  with check (true);

revoke all on table public.indicator_download_events from anon, authenticated;
grant select, insert, update, delete on table public.indicator_download_events to service_role;
grant usage, select on sequence public.indicator_download_events_id_seq to service_role;

alter table public.indicator_feed_settings
  add column if not exists token_ciphertext text,
  add column if not exists token_iv text,
  add column if not exists token_auth_tag text;

create table if not exists public.indicator_feed_token_rotations (
  id bigint generated by default as identity primary key,
  setting_key text not null,
  rotated_at timestamptz not null,
  rotated_by text not null,
  token_fingerprint text not null check (char_length(token_fingerprint) = 12)
);

create index if not exists idx_indicator_feed_token_rotations_time
  on public.indicator_feed_token_rotations (rotated_at desc);

alter table public.indicator_feed_token_rotations enable row level security;

drop policy if exists "service_role_indicator_feed_token_rotations" on public.indicator_feed_token_rotations;
create policy "service_role_indicator_feed_token_rotations"
  on public.indicator_feed_token_rotations
  for all
  to service_role
  using (true)
  with check (true);

revoke all on table public.indicator_feed_token_rotations from anon, authenticated;
grant select, insert, update, delete on table public.indicator_feed_token_rotations to service_role;
grant usage, select on sequence public.indicator_feed_token_rotations_id_seq to service_role;

create or replace function public.log_indicator_feed_token_rotation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.indicator_feed_token_rotations (
    setting_key,
    rotated_at,
    rotated_by,
    token_fingerprint
  ) values (
    new.setting_key,
    new.rotated_at,
    coalesce(nullif(new.rotated_by, ''), 'admin'),
    substring(new.token_hash from 1 for 12)
  );
  return new;
end;
$$;

revoke execute on function public.log_indicator_feed_token_rotation() from public, anon, authenticated;
grant execute on function public.log_indicator_feed_token_rotation() to service_role;

drop trigger if exists indicator_feed_token_rotation_audit on public.indicator_feed_settings;
create trigger indicator_feed_token_rotation_audit
after insert or update of token_hash on public.indicator_feed_settings
for each row execute function public.log_indicator_feed_token_rotation();
